# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - curl https://cli-assets.heroku.com/install.sh | sh
          - heroku --version
          - echo "\n
            machine api.heroku.com\n
              login $HEROKU_EMAIL\n
              password $HEROKU_TOKEN\n
            machine git.heroku.com\n
              login $HEROKU_EMAIL\n
              password $HEROKU_TOKEN" > prueba2.txt
          - cat prueba2.txt
