version: '3'

services:
  hotel:
    build: .
    ports:
      - 4200:4200
    volumes:
      - .:/home/app
    mem_limit: 3g
    command: ng run hotel:serve --host=0.0.0.0 --port=4200

  guest:
    build: .
    mem_limit: 3g
    ports:
      - 4201:4201
    volumes:
      - .:/home/app
    command: ng run guest:serve --host=0.0.0.0 --port=4201

  employer:
    mem_limit: 3g
    build: .
    ports:
      - 4202:4202
    volumes:
      - .:/home/app
    command: ng run mobile:serve --host=0.0.0.0 --port=4202

networks:
  default:
    external:
      name: contler_network
