version: '3'

services:
  hotel:
    build: .
    ports:
      - 4200:4200
    volumes:
      - .:/home/app
    command: ng run hotel:serve --host=0.0.0.0 --port=4200

  guest:
    build: .
    ports:
      - 4201:4201
    volumes:
      - .:/home/app
    command: ng run guest:serve --host=0.0.0.0 --port=4201

networks:
  default:
    external:
      name: contler_network
