# This is a basic workflow to help you get started with Actions

name: linter and build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # The ref command explicitly sets the commit to be checked out as the latest commit from the pull request that was initiated.
          ref: ${{ github.event.pull_request.head.ref }}
          # fetch-depth is set to 0 then then the entire history of commits is fetched
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          id: npm-cache
          path: ./node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm i
        if: steps.npm-cache.outputs.cache-hit != 'true'

      - name: check affected lint
        run: npm run affected:apps -- --base=origin/master


      - name: check affected lint
        run: npm run affected:lint -- --base=origin/master

      - name: build affected apps
        run: npm run affected:build -- --base=origin/master

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
