# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # The ref command explicitly sets the commit to be checked out as the latest commit from the pull request that was initiated.
          ref: ${{ github.event.pull_request.head.ref }}
          # fetch-depth is set to 0 then then the entire history of commits is fetched
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_mod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_mod-

      - run: git fetch --no-tags --prune --depth=5 origin master

      - name: install dependencies
        run: npm ci

      #      - name: build hotel
      #        run: npm run build:qa:hotel
      - name: check affected apps
        run: npm run affected:apps -- --plain --base=origin/master
