# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    env:
      BEFORE_COMMIT: ${{ github.event.before }}
      AFTHER_COMMIT: ${{ github.event.after }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT: ${{ secrets.FIREBASE_DEV_PROJECT }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # The ref command explicitly sets the commit to be checked out as the latest commit from the pull request that was initiated.
          ref: ${{ github.event.pull_request.head.ref }}
          # fetch-depth is set to 0 then then the entire history of commits is fetched
          fetch-depth: 0

      - name: npm cahce
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      #      - name: install firebase
      #        run: npm i -g firebase-tools
      #
      #      - name: install dependencies
      #        run: npm i -s
      #        if: steps.npm-cache.outputs.cache-hit != 'true'
      #
      #      - name: check affected apps
      #        run: npm run affected:apps -- --base="$BEFORE_COMMIT" --head="$AFTHER_COMMIT"
      #
      #      - name: build affected apps
      #        run: npm run affected:build -- --base="$BEFORE_COMMIT" --head="$AFTHER_COMMIT" --configuration qa

      - name: deploy hotel
        run: node bin/deploy.js hotel
